import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
  TextInput,
  Linking,
  Alert,
  Share,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useEmergencyProfile } from '@/hooks/useEmergencyProfile';
import { getMedications } from '@/services/storage';
import type { EmergencyContact, EmergencyProfile } from '@/types';
import { Privacy } from '@/constants/privacy';
import { Colors, Spacing, BorderRadius, Typography, Shadow } from '@/constants/theme';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import PrivacyNotice from '@/components/ui/PrivacyNotice';

const BLOOD_TYPES = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'Unknown'];

export default function EmergencyScreen() {
  const { profile, loading, save } = useEmergencyProfile();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<EmergencyProfile>(profile);

  // Sync draft when profile loads
  React.useEffect(() => {
    setDraft(profile);
  }, [profile]);

  async function handleSave() {
    await save(draft);
    setEditing(false);
  }

  async function handleShare() {
    const meds = await getMedications();
    const medList = meds.map((m) => `• ${m.name} ${m.dose}`).join('\n');
    const text = `🚨 EMERGENCY MEDICAL INFO\n\nName: (see phone)\nBlood Type: ${profile.bloodType}\n\nAllergies:\n${profile.allergies.map((a) => `• ${a}`).join('\n') || 'None listed'}\n\nMedical Conditions:\n${profile.conditions.map((c) => `• ${c}`).join('\n') || 'None listed'}\n\nCurrent Medications:\n${medList || 'None listed'}\n\nEmergency Contacts:\n${profile.contacts.map((c) => `• ${c.name} (${c.relationship}): ${c.phone}`).join('\n') || 'None listed'}\n\nNotes: ${profile.additionalNotes || 'None'}\n\n(Generated by MedsMinder — all data stored locally on device)`;
    Share.share({ message: text, title: 'Emergency Medical Info' });
  }

  function callContact(phone: string) {
    Linking.openURL(`tel:${phone}`);
  }

  const meds = useCurrentMedications();

  return (
    <SafeAreaView style={styles.safeArea} edges={['top']}>
      <View style={styles.header}>
        <Text style={styles.title}>Emergency Profile</Text>
        <TouchableOpacity
          onPress={editing ? handleSave : () => setEditing(true)}
          style={styles.editBtn}
        >
          <Ionicons name={editing ? 'checkmark' : 'create-outline'} size={20} color={Colors.textOnPrimary} />
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <PrivacyNotice message={Privacy.EMERGENCY_NOTICE} />

        {/* Emergency header card */}
        <Card style={styles.emergencyBanner}>
          <Ionicons name="alert-circle" size={28} color={Colors.danger} />
          <View style={styles.emergencyText}>
            <Text style={styles.emergencyTitle}>In an emergency</Text>
            <Text style={styles.emergencySubtext}>Show this screen to first responders or share via button below</Text>
          </View>
        </Card>

        {/* Blood type */}
        <Section title="Blood Type">
          {editing ? (
            <ScrollView horizontal showsHorizontalScrollIndicator={false}>
              <View style={styles.chipRow}>
                {BLOOD_TYPES.map((bt) => (
                  <TouchableOpacity
                    key={bt}
                    style={[styles.bloodTypeChip, draft.bloodType === bt && styles.bloodTypeChipActive]}
                    onPress={() => setDraft({ ...draft, bloodType: bt })}
                  >
                    <Text style={[styles.bloodTypeText, draft.bloodType === bt && styles.bloodTypeTextActive]}>
                      {bt}
                    </Text>
                  </TouchableOpacity>
                ))}
              </View>
            </ScrollView>
          ) : (
            <Text style={styles.bloodTypeDisplay}>{profile.bloodType || 'Not set'}</Text>
          )}
        </Section>

        {/* Allergies */}
        <Section title="🚨 Allergies">
          <TagEditor
            tags={editing ? draft.allergies : profile.allergies}
            onChange={(tags) => setDraft({ ...draft, allergies: tags })}
            placeholder="Add allergy..."
            editing={editing}
            emptyText="No allergies listed"
            badgeColor={Colors.dangerLight}
            textColor={Colors.dangerDark}
          />
        </Section>

        {/* Medical conditions */}
        <Section title="Medical Conditions">
          <TagEditor
            tags={editing ? draft.conditions : profile.conditions}
            onChange={(tags) => setDraft({ ...draft, conditions: tags })}
            placeholder="Add condition..."
            editing={editing}
            emptyText="No conditions listed"
            badgeColor={Colors.warningLight}
            textColor={Colors.warning}
          />
        </Section>

        {/* Current medications (auto from meds list) */}
        <Section title="💊 Current Medications">
          {meds.length === 0 ? (
            <Text style={styles.emptyText}>No medications added — go to the Medications tab to add some</Text>
          ) : (
            meds.map((m) => (
              <View key={m.id} style={styles.medRow}>
                <View style={[styles.medDot, { backgroundColor: m.color }]} />
                <Text style={styles.medName}>{m.name}</Text>
                <Text style={styles.medDose}>{m.dose}</Text>
              </View>
            ))
          )}
        </Section>

        {/* Emergency contacts */}
        <Section title="📞 Emergency Contacts">
          {(editing ? draft.contacts : profile.contacts).length === 0 && (
            <Text style={styles.emptyText}>No emergency contacts added</Text>
          )}
          {(editing ? draft.contacts : profile.contacts).map((contact) => (
            <ContactRow
              key={contact.id}
              contact={contact}
              editing={editing}
              onCall={() => callContact(contact.phone)}
              onDelete={() =>
                setDraft({
                  ...draft,
                  contacts: draft.contacts.filter((c) => c.id !== contact.id),
                })
              }
            />
          ))}
          {editing && (
            <AddContactForm
              onAdd={(contact) =>
                setDraft({ ...draft, contacts: [...draft.contacts, contact] })
              }
            />
          )}
        </Section>

        {/* Additional notes */}
        <Section title="Additional Notes">
          {editing ? (
            <TextInput
              style={styles.notesInput}
              value={draft.additionalNotes}
              onChangeText={(text) => setDraft({ ...draft, additionalNotes: text })}
              placeholder="Doctor names, hospital preferences, insurance info..."
              placeholderTextColor={Colors.textLight}
              multiline
            />
          ) : (
            <Text style={styles.notesText}>
              {profile.additionalNotes || 'No additional notes'}
            </Text>
          )}
        </Section>

        <Button
          label="Share Emergency Info"
          onPress={handleShare}
          variant="ghost"
          icon={<Ionicons name="share-outline" size={18} color={Colors.primary} />}
        />

        {editing && (
          <Button
            label="Cancel"
            onPress={() => { setDraft(profile); setEditing(false); }}
            variant="ghost"
          />
        )}

        <View style={styles.bottomPad} />
      </ScrollView>
    </SafeAreaView>
  );
}

function useCurrentMedications() {
  const [meds, setMeds] = useState<Awaited<ReturnType<typeof getMedications>>>([]);
  React.useEffect(() => {
    getMedications().then(setMeds);
  }, []);
  return meds;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card style={styles.section}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {children}
    </Card>
  );
}

function TagEditor({
  tags,
  onChange,
  placeholder,
  editing,
  emptyText,
  badgeColor,
  textColor,
}: {
  tags: string[];
  onChange: (tags: string[]) => void;
  placeholder: string;
  editing: boolean;
  emptyText: string;
  badgeColor: string;
  textColor: string;
}) {
  const [input, setInput] = useState('');

  function addTag() {
    if (!input.trim()) return;
    onChange([...tags, input.trim()]);
    setInput('');
  }

  return (
    <View style={styles.tagContainer}>
      <View style={styles.tagRow}>
        {tags.length === 0 && <Text style={styles.emptyText}>{emptyText}</Text>}
        {tags.map((tag) => (
          <TouchableOpacity
            key={tag}
            style={[styles.tag, { backgroundColor: badgeColor }]}
            onPress={editing ? () => onChange(tags.filter((t) => t !== tag)) : undefined}
          >
            <Text style={[styles.tagText, { color: textColor }]}>{tag}</Text>
            {editing && <Ionicons name="close" size={12} color={textColor} />}
          </TouchableOpacity>
        ))}
      </View>
      {editing && (
        <View style={styles.tagInputRow}>
          <TextInput
            style={styles.tagInput}
            value={input}
            onChangeText={setInput}
            placeholder={placeholder}
            placeholderTextColor={Colors.textLight}
            returnKeyType="done"
            onSubmitEditing={addTag}
          />
          <TouchableOpacity onPress={addTag} style={styles.tagAddBtn}>
            <Ionicons name="add" size={18} color={Colors.textOnPrimary} />
          </TouchableOpacity>
        </View>
      )}
    </View>
  );
}

function ContactRow({
  contact,
  editing,
  onCall,
  onDelete,
}: {
  contact: EmergencyContact;
  editing: boolean;
  onCall: () => void;
  onDelete: () => void;
}) {
  return (
    <View style={styles.contactRow}>
      <View style={styles.contactIcon}>
        <Ionicons name="person" size={18} color={Colors.primary} />
      </View>
      <View style={styles.contactInfo}>
        <Text style={styles.contactName}>{contact.name}</Text>
        <Text style={styles.contactRelation}>{contact.relationship} · {contact.phone}</Text>
      </View>
      {editing ? (
        <TouchableOpacity onPress={onDelete}>
          <Ionicons name="trash-outline" size={18} color={Colors.danger} />
        </TouchableOpacity>
      ) : (
        <TouchableOpacity onPress={onCall} style={styles.callBtn}>
          <Ionicons name="call" size={16} color={Colors.textOnPrimary} />
        </TouchableOpacity>
      )}
    </View>
  );
}

function AddContactForm({ onAdd }: { onAdd: (c: EmergencyContact) => void }) {
  const [name, setName] = useState('');
  const [relation, setRelation] = useState('');
  const [phone, setPhone] = useState('');

  function handleAdd() {
    if (!name.trim() || !phone.trim()) return;
    onAdd({ id: `contact-${Date.now()}`, name: name.trim(), relationship: relation.trim(), phone: phone.trim() });
    setName(''); setRelation(''); setPhone('');
  }

  return (
    <View style={styles.addContactForm}>
      <Text style={styles.addContactTitle}>Add Contact</Text>
      <TextInput style={styles.contactInput} value={name} onChangeText={setName} placeholder="Name" placeholderTextColor={Colors.textLight} />
      <TextInput style={styles.contactInput} value={relation} onChangeText={setRelation} placeholder="Relationship (e.g. Spouse)" placeholderTextColor={Colors.textLight} />
      <TextInput style={styles.contactInput} value={phone} onChangeText={setPhone} placeholder="Phone number" placeholderTextColor={Colors.textLight} keyboardType="phone-pad" />
      <Button label="Add Contact" onPress={handleAdd} variant="secondary" size="sm" disabled={!name.trim() || !phone.trim()} />
    </View>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  title: { ...Typography.h2, color: Colors.text },
  editBtn: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...Shadow.sm,
  },
  scroll: { flex: 1 },
  content: { padding: Spacing.lg, gap: Spacing.md },
  emergencyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.dangerLight,
    borderWidth: 1,
    borderColor: Colors.danger,
  },
  emergencyText: { flex: 1 },
  emergencyTitle: { ...Typography.h4, color: Colors.dangerDark },
  emergencySubtext: { ...Typography.bodySmall, color: Colors.dangerDark, lineHeight: 18 },
  section: { gap: Spacing.sm },
  sectionTitle: { ...Typography.h4, color: Colors.text },
  bloodTypeDisplay: { ...Typography.h2, color: Colors.primary, fontWeight: '700' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  bloodTypeChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: BorderRadius.pill,
    borderWidth: 2,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
  },
  bloodTypeChipActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  bloodTypeText: { ...Typography.bodySmall, color: Colors.textSecondary, fontWeight: '700' },
  bloodTypeTextActive: { color: Colors.textOnPrimary },
  tagContainer: { gap: Spacing.sm },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.xs },
  tag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: BorderRadius.pill,
  },
  tagText: { ...Typography.bodySmall, fontWeight: '600' },
  tagInputRow: { flexDirection: 'row', gap: Spacing.sm },
  tagInput: {
    flex: 1,
    backgroundColor: Colors.background,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    ...Typography.body,
    color: Colors.text,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  tagAddBtn: {
    width: 38,
    height: 38,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: { ...Typography.body, color: Colors.textLight, fontStyle: 'italic' },
  medRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  medDot: { width: 10, height: 10, borderRadius: 5 },
  medName: { ...Typography.body, color: Colors.text, fontWeight: '600', flex: 1 },
  medDose: { ...Typography.bodySmall, color: Colors.textSecondary },
  contactRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  contactIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactInfo: { flex: 1 },
  contactName: { ...Typography.bodySmall, color: Colors.text, fontWeight: '600' },
  contactRelation: { ...Typography.caption, color: Colors.textSecondary },
  callBtn: {
    width: 34,
    height: 34,
    borderRadius: BorderRadius.pill,
    backgroundColor: Colors.success,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addContactForm: { gap: Spacing.sm, marginTop: Spacing.sm, padding: Spacing.sm, backgroundColor: Colors.background, borderRadius: BorderRadius.md },
  addContactTitle: { ...Typography.label, color: Colors.primaryDark },
  contactInput: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.md,
    padding: Spacing.sm,
    ...Typography.body,
    color: Colors.text,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  notesInput: {
    backgroundColor: Colors.background,
    borderRadius: BorderRadius.md,
    padding: Spacing.sm,
    minHeight: 80,
    textAlignVertical: 'top',
    ...Typography.body,
    color: Colors.text,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  notesText: { ...Typography.body, color: Colors.textSecondary, lineHeight: 22 },
  bottomPad: { height: 100 },
});
